config/routes.rb
Testsearch::Application.routes.draw do

  resources :search_suggestions

  root 'pages#welcome'
  #root 'products#index'

  get 'pages/welcome'
  get 'pages/extra'
  get "/products/:id" => "products#index"
  
  resources :products do#, :only => [:index, :edit, :update]
    collection { post :import }
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
  match ':controller(/:action(/:id))', :via => :get
end

app/models/product.rb
class Product < ActiveRecord::Base

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			Product.create! row.to_hash
		end
	end

	def self.search(term)
		where("productcode ILIKE :term or description ILIKE :term or keyword ILIKE :term", term: "%#{term}%")
	end

end

app/models/search_suggestion.rb
class SearchSuggestion < ActiveRecord::Base

	def self.terms_for(prefix)
		suggestions = where("term ILIKE ?", "%#{prefix}_%")
		suggestions.order("popularity desc").limit(10).pluck(:term)
	end

	def self.index_products
		Product.find_each do |product|
			index_term(product.itemcode)
			index_term(product.productcode)
			index_term(product.description)
			index_term(product.keyword)
			product.description.split.each { |t| index_term(t) }
		end
	end

	def self.index_term(term)
		where(term: term.downcase).first_or_initialize.tap do |suggestion|
			suggestion.increment! :popularity
		end
	end

	
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def welcome
  	@products = Product.all
  end

  def extra

  end

end

app/controllers/products_controller.rb
require 'csv'
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def import
    Product.import(params[:file])
    redirect_to root_url, notice: "CSV Imported"
  end

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @products = Product.search(params[:search])
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  def urlLink
    @product = Product.url(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:itemcode, :productcode, :description, :keyword, :url, :image)
    end
end

app/controllers/search_suggestions_controller.rb
class SearchSuggestionsController < ApplicationController
	def index
		#render json: %w[foo bar]
		render json: SearchSuggestion.terms_for(params[:term])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_suggestions_helper.rb
module SearchSuggestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testsearch</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
  
<%= yield %>

</body>
</html>

app/views/pages/extra.html.erb
<h1>Pages#extra</h1>
<p>Find me in app/views/pages/extra.html.erb</p>

app/views/pages/welcome.html.erb
<div class="welcomeSearch">
	<%= form_tag products_path, method: :get do %>
  		<%= text_field_tag :search, params[:search], size: 30, :value => "", :placeholder => "Search here..." %>
  		<%= submit_tag "search", name: nil %>
	<% end %>
</div>

<br />
<%= link_to("Search page full", {:controller => 'products', :action => 'index'}) %>
<br />

<h1>Import</h1>
<%= form_tag import_products_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :itemcode %><br>
    <%= f.text_field :itemcode %>
  </div>
  <div class="field">
    <%= f.label :productcode %><br>
    <%= f.text_field :productcode %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :keyword %><br>
    <%= f.text_field :keyword %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<br />
<%= link_to("Search page empty", {:controller => 'pages', :action => 'welcome'}) %>
<br />


<h3>Listing products</h3>

<table id="tableimg" border=1>
  <thead>
    <tr>
      <!--<th>itemcode</th>-->
      <th>Productcode</th>
      <th>Description</th>
      <th>Image</th>
      <!--<th></th>
      <th></th>
      <th></th>-->
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <!--<td><%= product.itemcode %>-->
        <td><%= product.productcode %></td>
        <td><%= product.description %></td>
        <td><%= link_to image_tag(product.image), product.url %></td>
        <!--<td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--
<%= link_to 'New Product', new_product_path %>
-->

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Itemcode:</strong>
  <%= @product.itemcode %>
</p>

<p>
  <strong>Productcode:</strong>
  <%= @product.productcode %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Keyword:</strong>
  <%= @product.keyword %>
</p>

<p>
  <strong>Url:</strong>
  <%= @product.url %>
</p>

<p>
  <strong>Image:</strong>
  <%= @product.image %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>